name: Build Docker

on:
  pull_request:

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: "${{ github.ref }}-${{ github.workflow }}"
  cancel-in-progress: true

jobs:
  build_docker:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Display envvars
        run: env

      - name: Install Just
        run: curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | sudo bash -s -- --to /usr/local/bin

      - name: Test Docker Build
        run: just docker-build

      - name: Copy Artifacts
        run: docker-compose -f docker/compose/copy-debs.yaml up

      - name: Archive Artifacts
        run: zip -r splinter-pr${{ github.event.number }}.zip build/*

      - uses: actions/upload-artifact@v2
        with:
          name: splinter-pr${{ github.event.number }}
          path: splinter-pr*.zip
